import { Database } from "bun:sqlite";
import { drizzle, type BunSQLiteDatabase } from "drizzle-orm/bun-sqlite";
import { migrate } from "drizzle-orm/bun-sqlite/migrator";
import { mkdirSync } from "fs";
import { dirname, join } from "path";
import * as schema from "./schema";

export type Db = BunSQLiteDatabase<typeof schema>;

let _db: Db | null = null;

// Migration files are generated by `bun run db:generate` into leettui/drizzle/.
// Resolve relative to this source file (src/db) so it works regardless of cwd.
const MIGRATIONS_FOLDER = join(import.meta.dir, "..", "..", "drizzle");

export function openDatabase(dbPath: string): Db {
  if (_db) return _db;

  mkdirSync(dirname(dbPath), { recursive: true });
  const sqlite = new Database(dbPath);
  sqlite.exec("PRAGMA journal_mode = WAL");
  sqlite.exec("PRAGMA foreign_keys = ON");

  _db = drizzle(sqlite, { schema });

  // Apply any pending migrations on startup (creates tables on a fresh DB).
  migrate(_db, { migrationsFolder: MIGRATIONS_FOLDER });

  return _db;
}

export function getDb(): Db {
  if (!_db) throw new Error("Database not initialized");
  return _db;
}
